"AM: BEGIN OF .vim/syntax/namd.vim
syn sync clear
syn sync fromstart

syn match Comment "[#].*$"
"floating point number, with dot, optional exponent
syn match cFloat "\d\+\.\d*\(e[-+]\=\d\+\)\=[fl]\="
"floating point number, starting with a dot, optional exponent
syn match cFloat "\.\d\+\(e[-+]\=\d\+\)\=[fl]\=\>"
"floating point number, without dot, with exponent
syn match cFloat "\d\+e[-+]\=\d\+[fl]\=\>"
syn match cNumber "0x\x\+\(u\=l\{0,2}\|ll\=u\)\>"
syn match cNumber "\<[-+]\=\d\+\>"
highlight def link cNumber Constant
highlight def link cFloat Constant

syn match Title "^\*.*$"
syn keyword Identifier if label stream calc goto incr stop open read write
syn keyword Identifier writ set return else then endif decr
syn keyword Identifier ente enter mant mantim 
syn region Special start="sele" end="end"

syn match Statement "structure"
syn match Statement "coordinates"
syn match Statement "outputName"
syn match Statement "temperature"
syn match Statement "inputname"

syn match Statement "binCoordinates"
syn match Statement "binVelocities"
syn match Statement "extendedSystem"
syn match Statement "firsttimestep"
syn match Statement "paraTypeCharmm"
syn match Statement "parameters"
syn match Statement "cellBasisVector*"
syn match Statement "cellOrigin"
syn match Statement "wrapWater"
syn match Statement "wrapAll"
syn match Statement "exclude"
syn match Statement "1-4scaling"
syn match Statement "cutoff"
syn match Statement "switching"
syn match Statement "switchdist"
syn match Statement "pairlistdist"
syn match Statement "timestep"
syn match Statement "rigidBonds"
syn match Statement "nonbondedFreq"
syn match Statement "fullElectFrequency"
syn match Statement "stepspercycle"
syn match Statement "^\s*dyna\w*\>"
syn match Statement "^\s*edif\w*\>"
syn match Statement "^\s*emap\w*\>"
syn match Statement "^\s*ener\w*\>"
syn match Statement "^\s*ense\w*\>" 
syn match Statement "^\s*esta\w*\>"
syn match Statement "^\s*fact\w*\>"
syn match Statement "^\s*fluc\w*\>"
syn match Statement "^\s*four\w*\>"
syn match Statement "^\s*fqba\w*\>"
syn match Statement "^\s*galg\w*\>"
syn match Statement "^\s*game\w*\>"
syn match Statement "^\s*gbim\w*\>"
syn match Statement "^\s*gbmv\w*\>"
syn match Statement "^\s*gbor\w*\>"
syn match Statement "^\s*gbsw\w*\>"
syn match Statement "^\s*gene\w*\>"
syn match Statement "^\s*gete\w*\>"
syn match Statement "^\s*geth\w*\>"
syn match Statement "^\s*grap\w*\>"
syn match Statement "^\s*grid\w*\>"
syn match Statement "^\s*hbon\w*\>"
syn match Statement "^\s*hbtr\w*\>"
syn match Statement "^\s*hbui\w*\>"
syn match Statement "^\s*hqbm\w*\>"
syn match Statement "^\s*ic\w*\>"
syn match Statement "^\s*imag\w*\>"
syn match Statement "^\s*impa\w*\>"
syn match Statement "^\s*inqu\w*\>"
syn match Statement "^\s*inte\w*\>"
syn match Statement "^\s*join\w*\>"
syn match Statement "^\s*lone\w*\>"
syn match Statement "^\s*lupo\w*\>"
syn match Statement "^\s*mbon\w*\>"
syn match Statement "^\s*mcma\w*\>"
syn match Statement "^\s*mc\w*\>"
syn match Statement "^\s*merg\w*\>"
syn match Statement "^\s*mini\w*\>"
syn match Statement "^\s*mkcl\w*\>"
syn match Statement "^\s*mkpr\w*\>"
syn match Statement "^\s*mltc\w*\>"
syn match Statement "^\s*mmfp\w*\>"
syn match Statement "^\s*mmqm\w*\>"
syn match Statement "^\s*mndo\w*\>"
syn match Statement "^\s*molv\w*\>"
syn match Statement "^\s*moni\w*\>"
syn match Statement "^\s*move\w*\>"
syn match Statement "^\s*msca\w*\>"
syn match Statement "^\s*mts\w*\>"
syn match Statement "^\s*mull\w*\>"
syn match Statement "^\s*nbac\w*\>"
syn match Statement "^\s*nbon\w*\>"
syn match Statement "^\s*nmr\w*\>"
syn match Statement "^\s*noe\w*\>"
syn match Statement "^\s*nose\w*\>"
syn match Statement "^\s*olap\w*\>"
syn match Statement "^\s*para\w*\>"
syn match Statement "^\s*patc\w*\>"
syn match Statement "^\s*path\w*\>"
syn match Statement "^\s*pbeq\w*\>"
syn match Statement "^\s*pert\w*\>"
syn match Statement "^\s*pfba\w*\>"
syn match Statement "^\s*phmd\w*\>"
syn match Statement "^\s*phte\w*\>"
syn match Statement "^\s*pint\w*\>"
syn match Statement "^\s*pipf\w*\>"
syn match Statement "^\s*pnmi\w*\>"
syn match Statement "^\s*pola\w*\>"
syn match Statement "^\s*poly\w*\>"
syn match Statement "^\s*pres\w*\>"
syn match Statement "^\s*prin\w*\>"
syn match Statement "^\s*prot\w*\>"
syn match Statement "^\s*pull\w*\>"
syn match Statement "^\s*qche\w*\>"
syn match Statement "^\s*quan\w*\>"
syn match Statement "^\s*qub \w*\>"
syn match Statement "^\s*rate\w*\>"
syn match Statement "^\s*rcon\w*\>" 
syn match Statement "^\s*rdfs\w*\>"
syn match Statement "^\s*read\w*\>"
syn match Statement "^\s*rell\w*\>"
syn match Statement "^\s*rena\w*\>"
syn match Statement "^\s*repd\w*\>"
syn match Statement "^\s*repl\w*\>"
syn match Statement "^\s*resd\w*\>"
syn match Statement "^\s*rese\w*\>"
syn match Statement "^\s*rism\w*\>"
syn match Statement "^\s*rmsd\w*\>"
syn match Statement "^\s*rpat\w*\>"
syn match Statement "^\s*rush\w*\>"
syn match Statement "^\s*rxnc\w*\>"
syn match Statement "^\s*sasa\w*\>"
syn match Statement "^\s*sbou\w*\>"
syn match Statement "^\s*scal\w*\>"
syn match Statement "^\s*sccd\w*\>"
syn match Statement "^\s*serv\w*\>"
syn match Statement "^\s*shak\w*\>"
syn match Statement "^\s*shap\w*\>"
syn match Statement "^\s*shel\w*\>"
syn match Statement "^\s*show\w*\>"
syn match Statement "^\s*squa\w*\>"
syn match Statement "^\s*tamd\w*\>"
syn match Statement "^\s*test\w*\>"
syn match Statement "^\s*tmdi\w*\>"
syn match Statement "^\s*traj\w*\>"
syn match Statement "^\s*trav\w*\>"
syn match Statement "^\s*trek\w*\>"
syn match Statement "^\s*tsm \w*\>"
syn match Statement "^\s*umbr\w*\>"
syn match Statement "^\s*unbu\w*\>"
syn match Statement "^\s*upda\w*\>"
syn match Statement "^\s*vibr\w*\>"
syn match Statement "^\s*wham\w*\>"
syn match Statement "^\s*writ\w*\>"
syn match Statement "^\s*zmat\w*\>"
syn match Statement "^\s*zmod\w*\>"

syn match charmmParameter "[@?]\h\+"
syn match charmmParameter "[@?][{]\h\+[}]"
highlight def link charmmParameter ModeMsg

syn region CursorLine start="\<-\>\s*\([!].*\)\=$" end="\<" contains=Comment

let b:current_syntax = "charmm"
"AM: END OF .vim/syntax/charmm.vim

